data:
  summary_tokens: 256
  input_max: 1024
  train_classes: 150
  total_classes: 179
  k-folds: 5
  episodes: './data/episodes.txt'
  summary_with_scores: './data/RatedSummaryComprehensive.csv' 
  corpora_dir: './data/podcast_transcripts/'
  labels: 4
network:
  tokenizer: 'bert-large-uncased'
  finetune_base: 'bert-large-uncased'
  epochs: 5
  batch_size: 8
  fc1_out: 512
  dropout: 0.1


