data:
  summary_tokens: 256
  input_max: 1024
  train_classes: 150
  test_classes: 29
  k-folds: 5
  episodes: './data/episodes.txt'
  summary_with_scores: './data/RatedSummaryComprehensive.csv' 
  corpora_dir: './data/podcast_transcripts/'
network:
  tokenizer: 'bert-large-uncased'
  finetune: 'bert-large-uncased'

